name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Official Theos
      uses: actions/setup-theos@v1
      with:
        ios-version: 14.0

    - name: Compile Dylib File
      run: |
        export THEOS=$HOME/theos
        make clean
        make
        make package

    - name: Upload .deb
      uses: actions/upload-artifact@v4
      with:
        name: ColorRoadModMenu.deb
        path: packages/*.deb
